language: go

go:
  - 1.9

install:
  - go get -v github.com/j7b/jsplayground
  - go get github.com/gopherjs/gopherjs

script:
  - mv $GOPATH/bin ~/bin
  - go test -v github.com/j7b/jsplayground/...
  - gopherjs install github.com/j7b/jsplayground
  - jsplayground
  - mv /tmp/jsplayground-*/pkg .
  - mv $GOPATH/bin/*.* .
  - rm -rf $GOPATH ~/bin

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages

